from __future__ import annotations

from typing import Any

INTERFACE_VERSION = "phase11-agritech-interface-1.3.23"
DESIGN_SYSTEM_VERSION = "cocoaid-official-agritech-1.3.23"
WEATHER_GIS_UI_VERSION = "weather-gis-official-ui-1.2.0"
REPORT_PRESENTATION_VERSION = "official-office-report-1.1.0"


def interface_status() -> dict[str, Any]:
    return {
        "interface_id": "v3.interface",
        "version": INTERFACE_VERSION,
        "availability": "available",
        "maturity": "research_candidate",
        "design_system_version": DESIGN_SYSTEM_VERSION,
        "weather_gis_ui_version": WEATHER_GIS_UI_VERSION,
        "report_presentation_version": REPORT_PRESENTATION_VERSION,
        "theme": {
            "default": "official_white",
            "liquid_glass_enabled": False,
            "solid_surfaces": True,
            "logo_palette": ["#246b32", "#6fae22", "#ef8500", "#724413", "#172219"],
            "gradients_restricted_to": ["loading_bars", "progress_lines", "scan_lines"],
        },
        "landing": {
            "full_screen": True,
            "interactive_coconut_hologram": True,
            "slow_auto_rotation": True,
            "pointer_rotation": True,
            "keyboard_rotation": True,
            "scan_animation": True,
            "full_3d_hologram": True,
            "clean_landing_rehaul": True,
            "entry_hologram_enabled": False,
            "entry_background_carousel": True,
            "entry_background_count": 7,
            "entry_centered_orbits": True,
            "home_fullscreen": True,
            "home_hologram_only": True,
            "farmer_step_guidance": True,
            "full_bleed_farm_background": True,
            "transparent_hologram_stage": True,
            "parametric_coconut_mesh": True,
            "annotation_free_hologram": True,
            "white_orbit_rings": True,
            "thick_white_orbit_rings": True,
            "alternating_coconut_tree_mesh": True,
            "smooth_mesh_transition": True,
            "mature_brown_coconut_mesh": False,
            "white_mature_coconut_mesh": True,
            "mature_coconut_scale": 0.94,
            "spherical_mature_coconut_geometry": True,
            "scrollable_home_sections": True,
            "full_bleed_analytical_backgrounds": True,
            "guided_farmer_profile": True,
            "automatic_identity_step_advance": True,
            "farmer_friendly_map_controls": True,
            "focused_orange_farm_boundary": True,
            "progressive_map_first_profile": True,
            "geodesic_side_dimensions": True,
            "automatic_replanting_need": True,
            "loading_hologram": True,
        },
        "visualizations": {
            "long_term_forecast_weather_boundary": True,
            "embedded_weather_gis_forecast": False,
            "automatic_forecast_configuration": True,
            "farm_centered_forecast_map": True,
            "persistent_forecast_slider": True,
            "optional_forecast_calendar": True,
            "weather_gis_style_wind_overlay": True,
            "toggle_switch_map_layers": True,
            "hazard_event_calendar": True,
            "map_first_farm_health": True,
            "dedicated_pest_risk_workspace": True,
            "segmented_loading_progress": True,
            "chart_zoom": True,
            "chart_pan": True,
            "chart_reset": True,
            "chart_png_export": True,
            "chart_csv_export": True,
            "chart_fullscreen": True,
            "broadcast_style_hazard_visual": False,
            "period_consistent_hazard_weather": True,
            "visual_hazard_summary_cards": True,
            "map_first_health_calendar_side_rail": True,
            "enhanced_pest_risk_workspace": True,
            "hazard_satellite_news_overlay": True,
            "event_reactive_health_indicators": True,
            "synchronized_hazard_forecast_snapshot": True,
            "clipped_square_rehabilitation_grid": True,
            "geometric_cell_polygon_clipping": True,
            "highlighted_arrow_controls": True,
            "interactive_late_stage_workspaces": True,
            "automatic_phase9_phase10": True,
            "forecast_to_phase9_bootstrap": True,
        },
        "assistant_ui": {
            "transparent_holographic_sphere": True,
            "waiting_animation": True,
            "typing_animation": True,
            "loading_animation": True,
            "speaking_animation": True,
            "glass_cockpit_layout": True,
        },
        "audio": {
            "background_music_preserved": True,
            "voice_lines_preserved": True,
        },
        "accessibility": {
            "keyboard_hologram_controls": True,
            "reduced_motion_supported": True,
            "chart_aria_labels": True,
            "responsive_layout": True,
            "off_canvas_navigation": True,
            "non_blocking_navigation": True,
            "icon_only_navigation_state": True,
        },
    }
